### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by kaivongcom** [badsyntax/SassBeautify#11]
`*.[scss|sass]` 
> There was an error beautifying your Sass:
> 
> [Errno 2] No such file or directory
> 
> Does 'sass-convert' exist in PATH?'

`sass-convert` is OK. Sass 3.2.10 (Media Mark) on OSX 10.8.4

**Comment by kaivongcom** [comment]
`sass-convert test.scss`:

```
foo
  bar
    border: 1px solid red
```

**Comment by kaivongcom** [comment]
At a later date! Soz for the issue -- please close

**Comment by kaivongcom** [comment]
thanks for sharing and maintaining this plugin

**Comment by kaivongcom** [comment]
@dallasbpeters – from `Readme`:
`// Custom environment PATH.`
`"path": false,`

So either `false` or a Path

**Comment by field2** [comment]
Seems to be an issue again, after updateing OSX to El Capitan...

**Comment by zackphilipps** [comment]
:+1: Issue on El Capitan.

**Comment by li2274221** [comment]
:+1: Issue on El Capitan.

**Comment by li2274221** [comment]
and how to fix that?

**Comment by zackphilipps** [comment]
https://github.com/sass/sass/issues/1768

@endoplasmic had the answer that worked for me.

**Comment by zackphilipps** [comment]
At least until I update or reinstall Ruby.

**Comment by field2** [comment]
OK, I'm dumb, but what did you replace where it says GEM_NAME_HERE ?
sudo gem install -n /usr/local/bin GEM_NAME_HERE
I tried sudo gem install -n /usr/local/bin sass and although it installed the latest sass (I think), the error's still there.

**Comment by zackphilipps** [comment]
That should be correct. Are you using Homebrew? If so, run `brew doctor` to see if there's a permissions issue with your `/usr/local` directory. Or you could just `cd` to `/usr` and run `ls -l` to see the owner of the directory. It should be `you:admin` where `you` is your OSX username. [All is explained here.](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/El_Capitan_and_Homebrew.md)

If that's not the issue, then I don't know what is. :/

**Comment by field2** [comment]
Not using homebrew; should I be?

On Tue, Oct 13, 2015 at 11:30 AM, Zack Philipps notifications@github.com
wrote:

> That should be correct. Are you using Homebrew? If so, run brew doctor to
> see if there's a permissions issue with your /usr/local directory. Or you
> could just cd to /usr and run ls -l to see the owner of the directory. It
> should be you:admin where you is your OSX username. All is explained here.
> https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/El_Capitan_and_Homebrew.md
> 
> If that's not the issue, then I don't know what is. :/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/badsyntax/SassBeautify/issues/11#issuecomment-147751137
> .

##

**Comment by zackphilipps** [comment]
Not necessarily. Have you tried reinstalling the sass gem normally? Like `sudo gem install sass`.

**Comment by field2** [comment]
Yes, I have sass installed, but not homebrew; bre doctor says brew: command not found

**Comment by zackphilipps** [comment]
The only thing I can think of is maybe SassBeautify can't find the sass gem because the permissions/ownership need adjusted on your `/usr/local` directory. When El Capitan is installed it changes that, and they simply need to go back to the way they were. [Check this again](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/El_Capitan_and_Homebrew.md) and follow the steps, see if it helps.

**Comment by dajocarter** [comment]
I have permissions set correctly from doing the `chown` as Homebrew suggested, and I also ran `gem install -n /usr/local/bin sass`. This worked for me on the mac mini but on my macbook.

**Comment by zackphilipps** [comment]
Found a better fix I think. Under Preferences > Package Settings > SassBeautify > Settings – User add this line:

    "path": "/usr/local/bin"

Hopefully this will prevent having to run `gem install -n /usr/local/bin sass` over and over.

**Comment by dajocarter** [comment]
Adding the path to settings worked for me.
Thanks @zackphilipps :100:

**Comment by zackphilipps** [comment]
Sick! Thanks @badsyntax for pointing me to the readme. I tried that before and it didn't work, so I must've just screwed it up somehow.

**Comment by field2** [comment]
When I paste 

"path": "/usr/local/bin"

into my SassBeautify user settings, I get

Error trying to parse settings: Unexpected trailing characters in Packages/User/SassBeautify.sublime-settings:1:7

**Comment by field2** [comment]
{
"path": "/usr/local/bin"
}
worked for me!

**Comment by digitalcraftco** [comment]
Thank you! Path fixed worked for me on El Capitan. Was going crazy trying to re-install sass gems.

**Comment by mlabbe123** [comment]
Another happy sassBeautify user here, big thanks to @zackphilipps for the hint!

**Comment by danielhaim1** [comment]
gah. @zackphilipps latest solution keeps crashing my sublime :[

**Comment by danielhaim1** [comment]
Alright, just heads up this worked for me:

Open up terminal
Run: echo $PATH
Copy the entire PATH into the 'path' setting
Run: echo $GEM_PATH
Copy the entire GEM_PATH into the 'gemPath' setting

found here: https://github.com/badsyntax/SassBeautify#issues-with-ruby-sass-and-your-path

**Comment by Le-future** [comment]
I'm getting exactly the same problem since I upgraded my Macbook to El Capitaaan.

Did you find a solution?

**Comment by danielhaim1** [comment]
Yes, the solution above worked for me.

**Comment by Le-future** [comment]
Thanks for the help, my problem is at this point : 

Copy the entire GEM_PATH into the 'gemPath' setting

When I type this sentence, the terminal send me back a bank space without path

**Comment by Liquir-ice** [comment]
This solution fixed my problem

```
$ sudo gem install sass
$ which sass-convert
/usr/local/bin/sass-convert

# Change the sublime sassbeautify user preference
{
  "indent": 4,
  "dasherize": false,
  "old": false,
  "path": "/usr/local/bin/",
  "gemPath": false,
  "beautifyOnSave": true,
  "inlineComments": false,
  "useSingleQuotes": false
}
```

**Comment by Le-future** [comment]
Absolutely awesome @Liquir-ice , worked for me as well! Thanks very much 😃

**Comment by field2** [comment]
This problem's back under 10.13.1 High Sierra. Need to do 
`sudo gem install sass`

**Comment by RaphaelDDL** [comment]
From what I could see on this topic, every new OSX upgrade needs to reinstall sass. I updated to Mojave and had same issue, so reinstalling the gem as @field2 showed is the way to go on every update. 👍
