### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by CXHub** [badsyntax/SassBeautify#112]
Hi There,

First of all I would like to say that the plugin works great!
When I use Sassbeautify, the code becomes like the first class in the following example:

![Example](http://i68.tinypic.com/riw02b.png)

But I would like the indentation to be as in the second class in the example.
To fix this I use the default sublime action '_Indentation: Reindent lines_' afterwards.

Is this possible with Sassbeautify by default?

_FYI: I highlighted the code to show you the spacing._

Thanks in advance!

**Comment by owenleonard** [comment]
Change your SassBeautify user setting file to have the following setting:

  "indent": "t"

This will use tabs for indentation instead of spaces.

**Comment by CXHub** [comment]
This seems to be the solution, thanks a lot!

**Comment by sabbiseaan** [comment]
It wont work it still indent with space.

**Comment by sabbiseaan** [comment]
> It wont work it still indent with space.

Sorry its my bad with help of sublime indent with spaces option checked.
it work like charm 👍
