### ISSUE TITLE
SassBeautify doesn't work...

### ISSUE THREAD

**Issue by WilliamVercken** [badsyntax/SassBeautify#28]
Hi !
Sorry to borrow you with my issues !

I have a new PC at work, Windows 8 64 bits.
I wanted to test your example from your comment (from my feature request), and I noticed that it did not work at all for all my .scss files.

What I did, from the start to the bug :
- Download SublimeText 2.0.2 Portable here : http://www.sublimetext.com/2
- Unzip and launch it
- Open Console (View > Show Console)
- Install Package Control following instructions for Sublime Text 2 : https://sublime.wbond.net/installation#st2
- Restart
- Use Package Control to install SassBeautify
- Restart
- Open a file test.scss with this content : 
  <pre>.i-have-a-problem{color:blue; &.yes-me-too{color:red;} }</pre>
- Execute SassBeautify (I can see this message : "Beautifying your sass..." )
- Nothing happens. :(

Did I missed something ?
Is my computer the problem ? As a Freelance (anymore since the last week) I used SassBeautify on my Laptop with Windows 7 64 bits.

Thank you for your help.

**Comment by wijnandmet** [comment]
When I do "echo %path% I see a lot of information, but when I try SassBeautify then I get the error: 

There was an error beautifying your Sass:
[Errno 32] Broken pipe

No further error information is given. Is there anything I can do to fix it?
