### ISSUE TITLE
Path setting giving error

### ISSUE THREAD

**Issue by jitendravyas** [badsyntax/SassBeautify#52]
I'm on Ubuntu 14 and using RVM

and my $echo path is /home/jitendra/.rvm/gems/ruby-1.9.3-p327/bin:/home/jitendra/.rvm/gems/ruby-1.9.3-p327@global/bin:/home/jitendra/.rvm/rubies/ruby-1.9.3-p327/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/jitendra/.rvm/bin

When I paste this as a path value I get this error

Error trying to parse settings: Expected value in Packages/User/SassBeautify.sublime-settings:5:13

My setting file http://pastebin.com/SVbvqbR7

**Comment by martynchamberlin** [comment]
Perfect. I was actually getting this exact error on Mac OS X Yosemite and running `gem install sass` did the trick.
