### ISSUE TITLE
I have given path and gem_path but it's still not working. I'm on OSX 10

### ISSUE THREAD

**Issue by jitendravyas** [badsyntax/SassBeautify#66]
{
  "indent": 2,
  "dasherize": false,
  "old": false,
  "path": "/usr/local/share/npm/bin /Users/jitendravyas/.nvm/v0.10.33/bin /Users/jitendravyas/.rvm/gems/ruby-2.1.2/bin /Users/jitendravyas/.rvm/gems/ruby-2.1.2@global/bin /Users/jitendravyas/.rvm/rubies/ruby-2.1.2/bin /usr/local/bin /usr/local/bin /usr/local/sbin /usr/bin /bin /usr/sbin /sbin /Users/jitendravyas/.rvm/bin /Users/jitendravyas/.rvm/bin",
  "gemPath": "/Users/jitendravyas/.rvm/gems/ruby-2.1.2:/Users/jitendravyas/.rvm/gems/ruby-2.1.2@global",
  "beautifyOnSave": true,
  "inlineComments": false,
  "newlineBetweenSelectors": true
}

**Comment by badsyntax** [comment]
Closing due to lack of feedback.
