### ISSUE TITLE
Parenthesis are removed

### ISSUE THREAD

**Issue by svossen** [badsyntax/SassBeautify#69]
I add parentheses when I use a calculation in Sass. Sometimes because it is required, sometimes to improve readability.

I use the following code ```padding: ($bsu / 2) ($bsu / 2) ($bsu * 3.5) ($bsu / 2);``` . After beautify this becomes ```padding: $bsu / 2 $bsu / 2 $bsu * 3.5 $bsu / 2;``` . This doesn't influent the calculation, but I prefer adding the parenthesis because it improves readability.

Is it possible to prevent SassBeautify from removing the parentheses?

**Comment by jackocnr** [comment]
+1

**Comment by badsyntax** [comment]
I understand this to be an intentional optimisation done by sass-convert. Saying that, I have opened an issue in the Sass repo and will await for some feedback: https://github.com/sass/sass/issues/1614

**Comment by badsyntax** [comment]
This is now resolved in [Sass 3.4.11](http://sass-lang.com/documentation/file.SASS_CHANGELOG.html#3411_30_january_2015)! Update your Sass to get the fix.

**Comment by svossen** [comment]
I'm will update Sass. Thanks!
