### ISSUE TITLE
Variable interpolation marks are duplicated: #{$var} => #{#{$var}}

### ISSUE THREAD

**Issue by jdsteinbach** [badsyntax/SassBeautify#71]
This plugin doesn't handle variable interpolation correctly. It converts `#{$var}` into `#{#{$var}}` which throws an error in both Ruby Sass & Libsass.

**Comment by badsyntax** [comment]
Can you provide some Sass code to demonstrate this issue? 

Also what version of Sass do you have installed on your system?

**Comment by jdsteinbach** [comment]
```
$sidebar-width: 100px;
$colors: (
	red: #f00,
	blue: #00f,
	green: #0f0
);

.el {
	width: calc( 100% - #{$sidebar-width});
}

@each $name, $value in $colors {
	.color-#{$name} {
		color: $value;
	}
}
```

Becomes: 
```
$sidebar-width: 100px;
$colors: (red: #f00, blue: #00f, green: #0f0);

.parent {
	.child {
		width: calc( 100% - #{#{$sidebar-width}});
	}
}

@each $name, $value in $colors {
	.color-#{$name} {
		color: $value;
	}
}
```

So the bug I saw happens inside of `calc()`, but not inside an @each loop.

This all happens when I run SassBeautify in ST3, long before Sass gets involved, but if it helps, I've got Ruby Sass 3.4.7 installed and (npm) node-sass 2.0.0. I have no idea how ST3 or its plugins would know that - Sass is being managed by either Compass CLI (for Ruby) or Grunt (for node-sass) and ST3 is only an editor for me, not a compiler.

**Comment by badsyntax** [comment]
Refs #63

**Comment by badsyntax** [comment]
Sass is actually the beautifier here. This plugin uses `sass-convert` which is part of ruby sass. You need to upgrade your Sass to at least 3.4.9

**Comment by jdsteinbach** [comment]
On 3.4.10 now and no trouble at all, thanks!
