### ISSUE TITLE
[Errno 20] Not a directory

### ISSUE THREAD

**Issue by jitendravyas** [badsyntax/SassBeautify#72]
Getting this error

![monosnap d5gfo](https://cloud.githubusercontent.com/assets/77309/5974039/b608c7e6-a895-11e4-8258-d5fdbfda2545.jpg)

this is my setting file

`````
{
  "indent": 2,
  "dasherize": false,
  "old": false,
  "path": "/Users/jitendravyas/.rvm/gems/ruby-2.1.2/bin/sass",
  "gemPath": "/Users/jitendravyas/.rvm/gems/ruby-2.1.2/bin/sass",
  "beautifyOnSave": true,
  "inlineComments": false,
  "newlineBetweenSelectors": true
}
`````

**Comment by badsyntax** [comment]
Have you read the README? 

https://github.com/badsyntax/SassBeautify#compatibility-with-rvmrbenv

**Comment by jitendravyas** [comment]
@badsyntax Thanks. It's my mistake I should have cheked this before

**Comment by badsyntax** [comment]
@jitendravyas np, glad it's resolved :+1:
