### ISSUE TITLE
String quotes get changed from ' to " - should be the other way around

### ISSUE THREAD

**Issue by marshfire** [badsyntax/SassBeautify#81]
I'm using the autosave option in sublime and all ' quotes get changed to ". This leads to scss-lint errors. Is there a way to change the behavior?

**Comment by davetgreen** [comment]
+1 for this as a setting!

**Comment by NikolaMalich** [comment]
+1 would love to be able to set it to single quotes.

**Comment by PixelT** [comment]
+1

**Comment by PeterMK85** [comment]
+1

**Comment by iris00** [comment]
+++1

**Comment by jeanpierreb** [comment]
+1

**Comment by mintuhouse** [comment]
+1

**Comment by kkashou** [comment]
Any updates on this?

**Comment by cdmo** [comment]
+1

**Comment by ArnarTumi** [comment]
+1

**Comment by badsyntax** [comment]
Thanks to @mintuhouse 

This change has been merged into release 1.4.2 which should appear in the package channels soonish.

**Comment by badsyntax** [comment]
Ok it's updated in the package channels. You can upgrade SassBeautify from Sublime Text using the "Package Control: Upgrade Package" option in the command palette (ctrl/cmd + shift + p)
