### ISSUE TITLE
'sass-convert' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by KyleKeulen** [badsyntax/SassBeautify#92]
![error](https://cloud.githubusercontent.com/assets/12011327/9191889/5a82542e-3fd4-11e5-8613-7f983bc997c0.jpg)

**Comment by nguyentrongthanh** [comment]
me too

**Comment by josephbona** [comment]
Any resolution? I'm still having this issue

**Comment by mehas** [comment]
Seems to happen completely at random. The plugin will work fine for me for hours, then suddenly this error appears.

**I fixed it** by manually re-adding the Ruby dir (`C:\Ruby22-x64\bin` for me) to my system environment variables and restarting ST.

 _ST3 build 3114 on Windows 10._

**Comment by Oyshoboy** [comment]
Happened to me as well, Windows 10
