### ISSUE TITLE
[Errno 2] No such file or directory: 'sass-convert'

### ISSUE THREAD

**Issue by maxleistner** [badsyntax/SassBeautify#97]
I am working on Mac OS X El Capitan and installed Ruby via Homebrew. 
In SublimeText 3 i installed SassBeautify via PackageControl.

I get the following error trying to beatify my sass: 

`[Errno 2] No such file or directory: 'sass-convert'`

I also tried to echo the $PATH and the $GEM_PATH, BUT the $GEM_PATH is EMPTY!

Any ideas how to fix it?

**Comment by maxleistner** [comment]
Got it working by updating sass

**Comment by mkstix6** [comment]
I'm having this trouble. @maxleistner could you expand on your fix a little. I'm not sure exactly how to do what you describe.

**Comment by mkstix6** [comment]
I've just found this: https://github.com/badsyntax/SassBeautify#compatibility-with-rvmrbenv
Gonna give it a go.
